name: Music Pouch Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Music Pouch to S3
        run: npm i && npm run build && aws s3 sync build/ s3://www.musicpouch.us --delete && aws s3 sync build/ s3://musicpouch.us --delete
      - name: Update Cache Control
        run: aws s3 cp s3://www.musicpouch.us/index.html s3://www.musicpouch.us/index.html --metadata-directive REPLACE --cache-control no-cache && aws s3 cp s3://musicpouch.us/index.html s3://musicpouch.us/index.html --metadata-directive REPLACE --cache-control no-cache
